[package]
name = "nelo"
version = "0.1.0"
edition = "2024"
authors = ["James Dadabo"]
repository = "https://github.com/James51332/nelo/tree/rust"
description = "A stateless, timeline-driven animation engine for explorable visual animations."
readme = "README.md"
license = "MIT"
keywords = ["animation", "video", "graphics"]
categories = ["graphics", "multimedia::video"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_log = { version = "1.0.0", features = ["color", "wasm-bindgen"] }
env_logger = "0.11.11"
log = "0.4.33"
pollster = "0.4.0"
wasm-bindgen = "0.2.126"
wasm-bindgen-futures = "0.4.76"
wgpu = "29.0.3"
winit = "0.30.13"

