[workspace]
resolver = "3"
members = ["native"]
 
[package]
name = "nelo"
version = "0.2.0"
edition = "2024"
authors = ["James Dadabo"]
repository = "https://github.com/James51332/nelo/tree/rust"
description = "A stateless, timeline-driven animation engine for explorable visual animations."
readme = "README.md"
license = "MIT"
keywords = ["animation", "video", "graphics"]
categories = ["graphics", "multimedia::video"]

[dependencies]
log = "0.4.33"
wgpu = "29.0.3"
bytemuck = { version = "1", features = ["derive"] }
glam = { version = "0.33.2", features = ["bytemuck"] }
pollster = "0.4.0"

[dev-dependencies]
png = "0.17"
